// See https://aka.ms/new-console-template for more information
Console.WriteLine($"Number of bytes of sbyte type in memory is {sizeof(sbyte)}");
Console.WriteLine($"Minimum of bytes of sbyte type in memory is {sbyte.MinValue}");
Console.WriteLine($"Maximum of bytes of sbyte type in memory is {sbyte.MaxValue}");
Console.WriteLine();
Console.WriteLine($"Number of bytes of byte type in memory is {sizeof(byte)}");
Console.WriteLine($"Minimum of bytes of byte type in memory is {byte.MinValue}");
Console.WriteLine($"Maximum of bytes of byte type in memory is {byte.MaxValue}");
Console.WriteLine();
Console.WriteLine($"Number of bytes of short type in memory is {sizeof(short)}");
Console.WriteLine($"Minimum of bytes of short type in memory is {short.MinValue}");
Console.WriteLine($"Maximum of bytes of short type in memory is {short.MaxValue}");
Console.WriteLine();
Console.WriteLine($"Number of bytes of ushort type in memory is {sizeof(ushort)}");
Console.WriteLine($"Minimum of bytes of ushort type in memory is {ushort.MinValue}");
Console.WriteLine($"Maximum of bytes of ushort type in memory is {ushort.MaxValue}");
Console.WriteLine();
Console.WriteLine($"Number of bytes of int type in memory is {sizeof(int)}");
Console.WriteLine($"Minimum of bytes of int type in memory is {int.MinValue}");
Console.WriteLine($"Maximum of bytes of int type in memory is {int.MaxValue}");
Console.WriteLine();
Console.WriteLine($"Number of bytes of uint type in memory is {sizeof(uint)}");
Console.WriteLine($"Minimum of bytes of uint type in memory is {uint.MinValue}");
Console.WriteLine($"Maximum of bytes of uint type in memory is {uint.MaxValue}");
Console.WriteLine();
Console.WriteLine($"Number of bytes of long type in memory is {sizeof(long)}");
Console.WriteLine($"Minimum of bytes of long type in memory is {long.MinValue}");
Console.WriteLine($"Maximum of bytes of long type in memory is {long.MaxValue}");
Console.WriteLine();
Console.WriteLine($"Number of bytes of ulong type in memory is {sizeof(ulong)}");
Console.WriteLine($"Minimum of bytes of ulong type in memory is {ulong.MinValue}");
Console.WriteLine($"Maximum of bytes of ulong type in memory is {ulong.MaxValue}");
Console.WriteLine();
Console.WriteLine($"Number of bytes of float type in memory is {sizeof(float)}");
Console.WriteLine($"Minimum of bytes of float type in memory is {float.MinValue}");
Console.WriteLine($"Maximum of bytes of float type in memory is {float.MaxValue}");
Console.WriteLine();
Console.WriteLine($"Number of bytes of double type in memory is {sizeof(double)}");
Console.WriteLine($"Minimum of bytes of double type in memory is {double.MinValue}");
Console.WriteLine($"Maximum of bytes of double type in memory is {double.MaxValue}");
Console.WriteLine();
Console.WriteLine($"Number of bytes of decimal type in memory is {sizeof(decimal)}");
Console.WriteLine($"Minimum of bytes of decimal type in memory is {decimal.MinValue}");
Console.WriteLine($"Maximum of bytes of decimal type in memory is {decimal.MaxValue}");
Console.WriteLine("End");